default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: conv_q_development

test:
  <<: *default
  database: conv_q_test

production:
  adapter: postgresql
  encoding: utf8
  database: d1to4ej4e7ouju
  port: 5432
  username: gmtbszglppwuuy
  password: <%= ENV['CONV_Q_DATABASE_PASSWORD'] %>
