default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: conv_q_development

test:
  <<: *default
  database: conv_q_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: bff253741d6d67
  password: <%= ENV['CONV_Q_DATABASE_PASSWORD'] %>
  database: heroku_bde28d9cdbaca51
